### ISSUE TITLE
Meta-data issues

### ISSUE THREAD

**Issue by hvr** [arowM/heterocephalus#1]
I noticed your recent package upload to Hackage as it was flagged by the matrix buildbot due to  packaging meta-data issues:

- The `description` ("Please see README.md") is not a proper description for your package (and Hackage will show a link to the README at the end of the description *if* the README exists; therefore that phrase is redundant), and hence this will cause poor experience for users (NB: your package won't be properly indexed by Hackage's package search feature and thus hurt its discoverability). See also [this posting](https://mail.haskell.org/pipermail/haskell-cafe/2016-November/125541.html) for more details.

- The build-dependencies have inaccurate versions bounds. Please be aware that accurate version bounds are mandated by the [PVP](http://pvp.haskell.org/), and adherence to the PVP is expected as part of the Hackage guidelines.  This has various knock off consequences, such as Hackage possibly not being able to generate Haddock documentation for your package, as well generally resulting in a poor experience for users since they'll run into the same compilation errors. Specifically, I've noticed the following compile error when trying to build `heterocephalus-1.0.0` with GHC 7.10.3 (which looks like the version bounds on  `template-haskell` are inaccurate).

```
Configuring component lib from heterocephalus-1.0.0
Preprocessing library heterocephalus-1.0.0...
[1 of 3] Compiling Text.Hamlet.Parse ( src/Text/Hamlet/Parse.hs, /tmp/matrix-worker/1479655690/dist-newstyle/build/x86_64-linux/ghc-7.10.3/heterocephalus-1.0.0/build/Text/Hamlet/Parse.o )
[2 of 3] Compiling Text.Heterocephalus.Parse ( src/Text/Heterocephalus/Parse.hs, /tmp/matrix-worker/1479655690/dist-newstyle/build/x86_64-linux/ghc-7.10.3/heterocephalus-1.0.0/build/Text/Heterocephalus/Parse.o )
[3 of 3] Compiling Text.Heterocephalus ( src/Text/Heterocephalus.hs, /tmp/matrix-worker/1479655690/dist-newstyle/build/x86_64-linux/ghc-7.10.3/heterocephalus-1.0.0/build/Text/Heterocephalus.o )

src/Text/Heterocephalus.hs:251:3:
    Constructor ‘DataConI’ should have 4 arguments, but has been given 3
    In the pattern: DataConI _ _ typeName
    In a stmt of a 'do' block: DataConI _ _ typeName <- reify conName
    In the expression:
      do { Just conName <- lookupValueName $ conToStr conStr;
           DataConI _ _ typeName <- reify conName;
           TyConI (DataD _ _ _ _ cons _) <- reify typeName;
           [fields] <- return
                         [fields | RecC name fields <- cons, name == conName];
           .... }
```

If you have any questions, please ask!

**Comment by hvr** [comment]
@arrowM almost there... now the buildbot complains about a different issue for GHC 7.8:

```
Configuring component lib from heterocephalus-1.0.0.1
Preprocessing library heterocephalus-1.0.0.1...
[1 of 3] Compiling Text.Hamlet.Parse ( src/Text/Hamlet/Parse.hs, /tmp/matrix-worker/1479722563/dist-newstyle/build/x86_64-linux/ghc-7.8.4/heterocephalus-1.0.0.1/build/Text/Hamlet/Parse.o )
[2 of 3] Compiling Text.Heterocephalus.Parse ( src/Text/Heterocephalus/Parse.hs, /tmp/matrix-worker/1479722563/dist-newstyle/build/x86_64-linux/ghc-7.8.4/heterocephalus-1.0.0.1/build/Text/Heterocephalus/Parse.o )

src/Text/Heterocephalus/Parse.hs:136:43:
    Not in scope: ‘<$>’
    Perhaps you meant one of these:
      ‘<|>’ (imported from Text.ParserCombinators.Parsec),
      ‘<?>’ (imported from Text.ParserCombinators.Parsec)

src/Text/Heterocephalus/Parse.hs:281:28:
    Not in scope: ‘<$>’
    Perhaps you meant one of these:
      ‘<|>’ (imported from Text.ParserCombinators.Parsec),
      ‘<?>’ (imported from Text.ParserCombinators.Parsec)
```

If you don't want to support versions prior to AMP, just edit the lower bound on `base` to say e.g. `base >= 4.8` on https://hackage.haskell.org/package/heterocephalus-1.0.0.1/heterocephalus.cabal/edit

**Comment by arowM** [comment]
@hvr Thanks for notifying me again. I'll tackle on this.

**Comment by arowM** [comment]
I've released v1.0.0.2 that resolves this issue.

**Comment by hvr** [comment]
@arowM ...just wanted to confirm that v1.0.0.2 looks good to me! :-)

**Comment by arowM** [comment]
@hvr Oh, sorry...
If v1.0.0.2 still has any errors, please tell me. I'll reopen this issue.

**Comment by hvr** [comment]
everything's fine! :-)
