### ISSUE TITLE
parsing #{} is failed if both a operator and extra spaces are included

### ISSUE THREAD

**Issue by syocy** [arowM/heterocephalus#20]
README says..
> You can use functions and data constructors as well.
> ...
> #{ num + 3 }

But the code is failed if extra spaces are included.
```haskell
main :: IO ()
main = do
  let num = 1 :: Int
  print $ renderMarkup [compileText|foo #{num + 1}|]   -- not error
  print $ renderMarkup [compileText|foo #{ num + 1 }|] -- error!
```

error message:
```
/home/kaz/work/a-tour-of-go-in-haskell/app/Main.hs:28:24: error:
    • Exception when trying to run compile-time code:
        (line 1, column 12):
unexpected "+"
expecting "}"
CallStack (from HasCallStack):
  error, called at src/Text/Heterocephalus/Parse.hs:24:16 in heterocephalus-1.0.5.0-2gqcf9NMmCiCY3qY9vpQ6N:Text.Heterocephalus.Parse
      Code: template-haskell-2.11.1.0:Language.Haskell.TH.Quote.quoteExp
              compileText "foo #{ num + 1 }"
    • In the quasi-quotation: [compileText|foo #{ num + 1 }|]
```

**Comment by arowM** [comment]
Thanks!
I'll check it later.

**Comment by arowM** [comment]
@syocy I figured out that this unexpected behaviour is cased by `parseDeref` function exposed by `Text.Shakespeare.Base`.
I've created an [issue about it on `yesodweb/shakespeare`](https://github.com/yesodweb/shakespeare/issues/211).

If the issue on `yesodweb/shakespeare` is resolved, I'll update dependencies and release new version of `heterocephalus`.

**Comment by arowM** [comment]
`Shakespeare-2.0.14.1`, which fixes this bug, is available now on hackage and stackage.
A workaround for this issue is to specify dependent `shakespeare` version `=< 2.0.14.1` in your cabal file or `stack.yaml` (or use latest nightly build of stackage).

I'll close this issue.
Thanks for reporting, @syocy !
