### ISSUE TITLE
Use template for non-HTML?

### ISSUE THREAD

**Issue by schoettl** [arowM/heterocephalus#23]
This is more a question: Can I use this package to compile and render templates for non-HTML text?

What I need is a template engine that works well for configuration files, LaTeX, or LilyPond files. Am I right that this package is intended to be used with blaze-markup and blaze-markup is intended to be used for HTML/XML only.

In my case I would like to create LilyPond markup (similar to LaTeX):

```haskell
renderLilypondTemplate title = renderMarkup [compileText|
\header {
  title = "#{title}"
  tagline = ##f
}
|]
```
and the output is
```
\header {
  title = "
The Title
"
  tagline =
#
#
f
}
```

i.e. it inserts line breaks and `#` cannot appear in the template used without being modified.

Do you have an advice or know alternatives for non-HTML templates?

**Comment by cdepillabout** [comment]
@schoettl I think heterocephalus should work for your use-case.

The example you posted appears to work for me.  Are you getting a different result when running it?

```haskell
$ stack ghci --package heterocephalus --package blaze-markup
> :m Text.Heterocephalus Text.Blaze.Renderer.String
> :set -XTemplateHaskell -XQuasiQuotes
> :{
| let title = "hello"; in putStrLn $ renderMarkup [compileText|
| \header {
|   title = "#{title}"
|   tagline = ##f
| } |]
| :}

\header {
  title = "hello"
  tagline = ##f
} 
>
```

**Comment by schoettl** [comment]
Thank you for the quick response. Your example works for me.

I used `Text.Blaze.Renderer.Pretty` instead of `.String`, that was the problem!

I understand that `.Pretty` puts newlines before and after the placeholder. But the differing behavior regarding `##f` is weired.

From [`Text.Blaze.Renderer.String`](http://hackage.haskell.org/package/blaze-markup-0.8.2.1/docs/Text-Blaze-Renderer-String.html) doc:

> A renderer that produces a native Haskell String, mostly meant for debugging purposes.

I hope they won't remove it in a future release if it's moslty for debugging...

**Comment by cdepillabout** [comment]
I was using `Text.Blaze.Renderer.String` for demonstration (since it is what is being used in the example in the README and I just basically copy and pasted that code).

I think you're probably right that it would be a better idea to use `Text.Blaze.Renderer.Text` or `Text.Blaze.Renderer.Utf8` if you're doing anything other than just playing around with heterocephalus:

```haskell
$ stack ghci --package heterocephalus --package blaze-markup --package text
> :m Text.Heterocephalus Text.Blaze.Renderer.Text
> import Data.Text.Lazy.IO as Text
> :set -XTemplateHaskell -XQuasiQuotes
> :{
| let title = "hello"; in Text.putStrLn $ renderMarkup [compileText|\header {
|   title = "#{title}"
|   tagline = ##f
| } |]
| :}
\header {
  title = "hello"
  tagline = ##f
} 
>
```

I guess this issue can be closed, but if you have any other problems, feel free to re-open this issue!

Also, if you wanted to send a PR adding a note to the README about not using `Text.Blaze.Renderer.Pretty`, I'm sure it would be helpful to other users!

**Comment by arowM** [comment]
Thanks for trying heterocephalus, @schoettl .
Thanks for quick response, @cdepillabout .

I'll close this issue, but feel free to do as @cdepillabout says.
