### ISSUE TITLE
indentation is lost from the examples in the hackage docs

### ISSUE THREAD

**Issue by cdepillabout** [arowM/heterocephalus#8]
In functions like [`compileTextFileWith`](https://hackage.haskell.org/package/heterocephalus-1.0.2.0/docs/Text-Heterocephalus.html#v:compileTextFileWith), the indentation in the examples is lost in the Hackage documetation.

**Comment by arowM** [comment]
@cdepillabout Thanks. Do you have any idea for dealing with this?

**Comment by arowM** [comment]
I found that [this](https://github.com/sol/doctest#multi-line-input) will help me.
I'll do on this issue.

**Comment by arowM** [comment]
03c47cd3b8292604b30f39e551cc6a01a7e29974 fixes this issue.
Version 1.0.2.1 will fix this on Hackage.
